import type { Locale, TranslationKey } from "./types";

const translations: Record<Locale, Record<TranslationKey, string>> = {
  en: {
    appName: "Thruflux",
    appSlogan: "Built for speed. Direct for security. Simple by design.",
    statusLabel: "Connection Status",
    statusReady: "Ready",
    statusChecking: "Checking",
    statusNotReady: "Not ready",
    themeLight: "Light",
    themeDark: "Dark",
    sendTitle: "Send files",
    sendBody: "Share files with one or more receivers",
    receiveTitle: "Receive files",
    receiveBody: "Receive files from others with a simple code",
    sendScreenTitle: "Drop files here",
    sendScreenBody: "Drag and drop files or folders to begin",
    sendScreenHint: "Use buttons below to add files or folders",
    sendSelectFiles: "Select files",
    sendSelectFolders: "Select folders",
    sendSummaryFiles: "files selected",
    sendSummaryFolders: "folders selected",
    sendDropMoreHint: "You can still drop more files here",
    sendDropOverlay: "Add to selection",
    sendSizeUnknown: "Folder",
    sendConfirm: "Send",
    receiveScreenTitle: "Join a transfer",
    receiveScreenBody:
      "Enter the code shared by the sender to begin receiving files",
    receiveJoinCodeLabel: "Join code",
    receiveJoinCodePlaceholder: "THRU-JOIN-CODE-HERE",
    receiveJoinCodeHint: "You can get this code from the sender",
    receiveSaveDirectoryLabel: "Save location",
    receiveSaveDirectoryHint: "Choose where received files will be saved",
    receiveSaveDirectoryButton: "Select folder",
    receiveActionButton: "Receive",
    receiveOverwriteBody:
      "Turn off automatic resume and overwrite any existing files. This ensures the transfer starts from scratch.",
    receiveStartingTitle: "Getting ready",
    receiveStartingBody: "Preparing to receive your files",
    receiveConnectingTitle: "Connecting",
    receiveConnectingBody: "Trying to connect to your sender",
    receiveConnectedTitle: "Connected",
    receiveConnectedBody: "Connection is ready",
    receiveJoiningTitle: "Joining",
    receiveJoiningBody: "Checking your code and joining the transfer",
    receiveP2PStartTitle: "Building direct link",
    receiveP2PStartBody: "Setting up a fast path between devices",
    receiveP2PSuccessTitle: "Direct link ready",
    receiveP2PSuccessBody: "Your transfer path is established",
    receiveManifestTitle: "Reading file list",
    receiveManifestBody: "Getting the file plan from the sender",
    receiveManifestSizeLabel: "Manifest size",
    receiveManifestParsingTitle: "Preparing your transfer",
    receiveManifestParsingBody:
      "Checking file details and finding the best place to continue",
    receiveSecureLinkTitle: "Secure channel ready",
    receiveSecureLinkBody: "Preparing to move files",
    receiveTransferTitle: "Receiving files",
    receiveTransferBody: "Files are moving now",
    receiveExpectedFilesLabel: "Expected files",
    receiveExpectedSizeLabel: "Expected size",
    receiveThroughputLabel: "Current speed",
    receiveMovedLabel: "Moved",
    receiveSkippedLabel: "Skipped",
    receiveFilesDoneLabel: "Files done",
    receiveRouteLabel: "Route",
    receiveEtaLabel: "ETA",
    receivePercentLabel: "Progress",
    receiveRouteDirect: "Direct",
    receiveRouteRelayed: "Relayed",
    receiveStartFailedTitle: "Could not start receiving",
    receiveP2PFailedTitle: "Could not make a direct link",
    receiveManifestErrorTitle: "Could not read the file list",
    receiveIceNotReadyTitle: "Connection setup is not ready",
    receiveTransferFailedTitle: "Transfer stopped early",
    receiveTransferFailedBody: "The transfer ran into a problem and could not continue",
    receiveCompleteTitle: "Transfer complete",
    receiveCompleteBody: "All files were received successfully",
    receiveFailedBadge: "Failed",
    normalClosureToast: "Transfer session ended",
    backHome: "Back to Home",
    settingsTitle: "Settings",
    settingsWarning:
      "Unless you know what you are doing, it is recommended not to modify these values.",
    settingsPanelTitle: "For advanced users...",
    settingsPanelBody: "Tune transfer behavior",
    appVersionNote: "v0.3.2 Beta",
    appMadeBy: "Made by infiniteplayapps",
    updateAvailableTitle: "Update available",
    updateAvailableBody:
      "A new version is available. If you do not update, some features may not work properly.",
    updateNow: "Update now",
    engineNotReadyRestartTitle: "Engine connection is not ready",
    engineNotReadyRestartBody:
      "Thruflux cannot connect to its local engine right now. Please restart the app to recover.",
    restartAppNow: "Restart app",
    openSettings: "Open advanced settings",
    serverUrl: "Server URL",
    stunServer: "STUN server",
    turnServers: "TURN servers",
    forceTurn: "Force TURN",
    quicConnWindowBytes: "QUIC connection window bytes",
    quicStreamWindowBytes: "QUIC stream window bytes",
    overwrite: "Overwrite existing files",
    udpBufferBytes: "UDP buffer bytes",
    maxReceivers: "Max number of receivers",
    notificationSettingsTitle: "Notifications",
    notificationReceiverFinishedLabel: "Receiver transfer complete",
    notificationReceiverFinishedHint:
      "Alert when your receive session finishes",
    notificationSenderJoinedLabel: "New receiver joined",
    notificationSenderJoinedHint:
      "Alert when someone starts receiving from you",
    notificationSenderCompletedLabel:
      "Receiver transfer complete (sender side)",
    notificationSenderCompletedHint:
      "Alert when a receiver finishes downloading",
    notificationReceiverFinishedTitle: "Transfer complete",
    notificationReceiverFinishedBody: "Your received files are ready.",
    notificationSenderJoinedTitle: "New receiver connected",
    notificationSenderJoinedBody: "Receiver joined:",
    notificationSenderCompletedTitle: "Receiver finished",
    notificationSenderCompletedBody: "Receiver completed transfer:",
    notificationTransferFailedLabel: "Transfer failed",
    notificationTransferFailedHint: "Alert when a transfer fails on send or receive",
    notificationReceiverFailedTitle: "Receive failed",
    notificationReceiverFailedBody: "This transfer could not be completed.",
    notificationSenderFailedTitle: "Receiver transfer failed",
    notificationSenderFailedBody: "Receiver failed transfer:",
    serverUrlError: "Must start with ws:// or wss://",
    serverUrlHint: "Address used when creating or joining a transfer session",
    stunServerError: "Must start with stun://",
    stunServerHint: "Used to help establish direct connectivity",
    turnServersError: "Each entry must start with turn://",
    quicRelationError:
      "Stream window must be less than or equal to connection window",
    turnServersHint: "Enter one per line",
    forceTurnHint: "Force routed mode instead of direct connectivity",
    qcwHint: "Maximum buffer budget for the full connection",
    qswHint: "Maximum buffer budget for each stream",
    udpHint:
      "System UDP buffer target for transport throughput. Best-effort application, may be limited by OS.",
    maxReceiversHint: "How many receivers can join at once",
    overwriteHint: "When disabled, existing files are kept",
    autoResumeHint: "Disable overwrite to effectively allow auto resume",
    sendPreparingTitle: "Getting everything ready",
    sendPreparingBody: "Setting up your share request",
    sendConnectingTitle: "Connecting",
    sendConnectingBody: "Trying to reach the session service",
    sendConnectedTitle: "Connected",
    sendConnectedBody: "Connection is ready. Getting your share code",
    manifestBuildTitle: "Preparing your files",
    manifestBuildBody: "Scanning selected files and folders",
    manifestEncodingTitle: "Finalizing file list",
    manifestEncodingBody: "Packaging file details for transfer",
    manifestSealedTitle: "Ready to connect",
    manifestSealedBody: "File list is complete",
    manifestFilesCountLabel: "Items found",
    manifestTotalSizeLabel: "Total size",
    joinCodeTitle: "Share this code",
    joinCodeBody: "Ask receivers to enter this code to join your transfer",
    shareCode: "Share code",
    copyCode: "Copy code",
    codeCopiedMessage: "Code copied to clipboard",
    receiverListTitle: "Receivers",
    receiverWaiting: "Waiting for receivers",
    sendStartFailedTitle: "Could not start sending",
    connectionErrorTitle: "Connection issue",
    disconnectedTitle: "Connection ended",
    goHomeAbortFailedTitle: "Could not stop current task",
    dismiss: "Got it",
    sendNow: "Send Now",
    senderNoReceiversTitle: "Waiting for receivers",
    senderNoReceiversBody: "Share this code and wait for someone to join",
    senderTransfersTitle: "Active transfers",
    senderReceiverLabel: "Receiver",
    senderStatusOngoing: "Ongoing",
    senderStatusCompleted: "Completed",
    senderStatusFailed: "Failed",
    senderAbortReceiverButton: "Stop receiver",
    senderAbortReceiverFailedTitle: "Could not stop receiver",
    sendAbortButton: "Stop transfer",
    receiveAbortButton: "Stop transfer",
    receiveOpenFolderButton: "Open save folder",
    receiveRetryButton: "Retry",
    openFolderFailedTitle: "Could not open folder",
  },
};

const locale: Locale = "en";

export const t = (key: TranslationKey): string => translations[locale][key];
